x-configuration: &CONFIGURATION
  volumes:
    - .:/Source:ro
  working_dir: /Build
  command: bash -c "${COMPOSE_COMMAND-
    cmake -G Ninja /Source;
    ninja install;
    ctest -j 6 --timeout 10;}
    ${COMPOSE_APPEND- }"

services:

  ubuntu_24.04:
    image: srccomplexity/ubuntu:24.04
    build:
      context: docker/ubuntu/
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      args:
        TAG: "24.04"
    environment:
      - PLATFORM=ubuntu_24.04
    <<: *CONFIGURATION

  fedora_40:
    image: srccomplexity/fedora:40
    build:
      context: docker/fedora/
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      args:
        TAG: "40"
    environment:
      - PLATFORM=fedora_40
    <<: *CONFIGURATION
