version: 2.1
jobs:
  build:
    docker:
      - image: mlcollard/ubuntu:latest
    steps:
      - checkout
      - run:
          name: Build Project
          command: |
            mkdir build
            cd build
            cmake .. -G Ninja
            ninja
      - run:
          name: Run local tests
          command: |
            cd build
            ctest || true
      - run:
          name: Package
          command: |
            cd build
            cpack -G DEB


      # - run: cd build && ninja && ninja install
      # - run: cd build && ctest
